version: "3"
services:
  python:
    restart: always
    build: .
    container_name: "python3"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./app:/root/opt
    command: python /root/opt/main.py
